statuses:
- name: ready
  dir: ready
  prioritized: true
- name: doing
  dir: doing
- name: done
  dir: done
default_priority: med
editor: vi
id_length: 5
no_edit: false
priority:
  auto_compact: false
